#!/bin/bash
#
#
# automaçao DNS 
# Ruan Cesar

# variaveis
pasta="/etc/bind"
arq="named.conf.default-zones"
tudo1="/etc/network/interfaces"

shopt -s -o nounset

echo "instalaçao do DNS com configuraçao automatica"

# verificando privilegios
if sudo -n true 2>/dev/null; then
    echo "O usuário tem privilégios sudo."
    sleep 2
else
    echo " pfv tenha permiçao sudo para executar esse script"
    echo "saindo..... "
    sleep 3
    exit 1
fi

# atualizando o sistema
echo "atualizando o sistema"
sleep 2
apt-get update -y && apt-get upgrade -y
sleep 4

# verificando a instalaçao do programa

if [ comand -v bind9 &>/dev/null ]; then
    echo " o programa ja esta instalado "
    echo "saindo...."
    exit 1
else
    echo " instalando o DNS "
    sleep 2
fi

#instalando o programa
apt-get install bind9 -y
sleep 4


#perguntas necessarias

echo "configurando o ip da maquina"
echo "  "
echo "qual é o ip da maquina?"
read ip
echo "qual é a mask?"
read mask
echo "qual  o gateway?"
read gateway
echo "qual é o dominio do seu site? (sem www ) (com .com/.local)"
read site
echo "qual o dominio do seu site sem o (.com/.local)"
read site1
echo "qual é o ip do servidor web?"
read web

#Primeiro Arquivo

echo zone \"$site\"\ { >> $pasta/$arq
echo "      type master;" >> $pasta/$arq
echo        file \"$pasta/db.$site\"\; >> $pasta/$arq
echo "};" >> $pasta/$arq

#Segundo arquivo 

touch $pasta/db.$site
echo "; BIND reverse data file for empty rfc1918 zone" >> $pasta/db.$site
echo ";" >> $pasta/db.$site
echo "; DO NOT EDIT THIS FILE - it is used for multiple zones." >> $pasta/db.$site
echo "; Instead, copy it, edit named.conf, and use that copy." >> $pasta/db.$site
echo ";" >> $pasta/db.$site
echo '$TTL	86400' >> $pasta/db.$site
echo "@	IN	SOA	ns1.$site. root.$site. (" >> $pasta/db.$site
echo "			      1		; Serial" >> $pasta/db.$site
echo "			 604800		; Refresh" >> $pasta/db.$site
echo "			  86400		; Retry" >> $pasta/db.$site
echo "			2419200		; Expire" >> $pasta/db.$site
echo "			  86400 )	; Negative Cache TTL" >> $pasta/db.$site
echo ";" >> $pasta/db.$site
echo "@	    IN	NS  ns1.$site1.local." >> $pasta/db.$site
echo "ns1   IN  A   $web" >> $pasta/db.$site
echo "www   IN  A   $web" >> $pasta/db.$site
systemctl restart bind9


#configuraçao de ip da maquina

echo "source /etc/network/interface.d/*" > $tudo1
echo "auto lo" >>$tudo1
echo "iface lo inet loopback" >>$tudo1
echo "allow-hotplug enp0s3" >>$tudo1
echo "iface enp0s3 inet static" >>$tudo1
echo "address $ip" >>$tudo1
echo "netmask $mask" >>$tudo1
echo "gateway $gateway" >>$tudo1
/etc/init.d/networking restart

echo "fim"
rm -f $0
