#!/bin/bash
#
#
# automaçao DNS parte 2
# Ruan Cesar

# variaveis
pasta="/etc/bind"
arq="named.conf.default-zones"
tudo1="/etc/network/interfaces"

shopt -s -o nounset

echo "instalaçao do DNS com configuraçao automatica"

# verificando privilegios
if sudo -n true 2>/dev/null; then
    echo "O usuário tem privilégios sudo."
    sleep 2
else
    echo " pfv tenha permiçao sudo para executar esse script"
    echo "saindo..... "
    sleep 3
    exit 1
fi





#perguntas necessarias

echo "qual é o dominio do seu site? (sem www ) (com .com/.local)"
read site
echo "qual o dominio do seu site sem o (.com/.local)"
read site1
echo "qual é o ip do servidor web?"
read web

#Primeiro Arquivo

echo zone \"$site\"\ { >> $pasta/$arq
echo "      type master;" >> $pasta/$arq
echo        file \"$pasta/db.$site\"\; >> $pasta/$arq
echo "};" >> $pasta/$arq

#Segundo arquivo 

touch $pasta/db.$site
echo "; BIND reverse data file for empty rfc1918 zone" >> $pasta/db.$site
echo ";" >> $pasta/db.$site
echo "; DO NOT EDIT THIS FILE - it is used for multiple zones." >> $pasta/db.$site
echo "; Instead, copy it, edit named.conf, and use that copy." >> $pasta/db.$site
echo ";" >> $pasta/db.$site
echo '$TTL	86400' >> $pasta/db.$site
echo "@	IN	SOA	ns1.$site. root.$site. (" >> $pasta/db.$site
echo "			      1		; Serial" >> $pasta/db.$site
echo "			 604800		; Refresh" >> $pasta/db.$site
echo "			  86400		; Retry" >> $pasta/db.$site
echo "			2419200		; Expire" >> $pasta/db.$site
echo "			  86400 )	; Negative Cache TTL" >> $pasta/db.$site
echo ";" >> $pasta/db.$site
echo "@	    IN	NS  ns1.$site1.local." >> $pasta/db.$site
echo "ns1   IN  A   $web" >> $pasta/db.$site
echo "www   IN  A   $web" >> $pasta/db.$site
systemctl restart bind9

echo "fim"
